from django.db.models import Q
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from taggit.models import Tag
from .forms import PostForm
from .models import Post, Category
from .utils import visible_posts
from django.contrib.staticfiles import finders
from django.http import FileResponse

def service_worker(request):
    sw_path = finders.find("blog/sw.js") # root directory of the service worker
    return FileResponse(open(sw_path, "rb"), content_type="application/javascript")


def home(request):
    context = {
        'posts': visible_posts(request.user).order_by("-date_posted")
    }
    return render(request, 'blog/home.html', context)


def about(request):
    return render(request, 'blog/about.html', {'title': 'About'})


class PostListView(ListView):
    model = Post
    template_name = 'blog/home.html'
    context_object_name = 'posts'

    def get_queryset(self):
        queryset = visible_posts(self.request.user).prefetch_related("categories", "tags")
        # queryset is obtained through visible_posts() to make sure user can't see posts they don't have permission for
        # fetches categories and tags in the same query for efficiency

        category = self.request.GET.get("category")
        tag = self.request.GET.get("tag")
        q = self.request.GET.get("q", "").strip()

        if category:
            queryset = queryset.filter(categories__name__iexact=category)
            # iexact makes sure it matches even if the capitalisation of your search is different from the category/tag

        if tag:
            queryset = queryset.filter(tags__name__iexact=tag)

        if q:
            queryset = queryset.filter(
                Q(categories__name__icontains=q) |
                Q(tags__name__icontains=q) |
                Q(title__icontains=q)
            )
        #

        return queryset.order_by("-date_posted").distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all()
        context["tags"] = Tag.objects.all()
        context["selected_category"] = self.request.GET.get("category")
        context["selected_tag"] = self.request.GET.get("tag")
        context["q"] = self.request.GET.get("q", "")
        return context
        # lets the template generated by PostListView use information about the categories and tags

class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'

    def get_queryset(self):
        return visible_posts(self.request.user).order_by("-date_posted")


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    form_class = PostForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

