# Generated by Django 5.2.11 on 2026-03-28 10:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='posts_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='trusted_users',
            field=models.ManyToManyField(blank=True, related_name='trusted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
